### PR TITLE
Refactor GitHub runner

### PR DESCRIPTION
**Pull request by orta**
This is the core part of Peril, so as I was building out I just built it as one massive function. Reasonable for just getting something started, but it didn't have room to grow. 

So now it's a bunch of smaller functions. Not gonna merge till I got a few tests.

### CODE REVIEW

**Comment by flovilmart** [comment]
it's making progress:

```
2017-07-01T16:40:31.913283+00:00 app[web.1]: Error:  TypeError: Cannot read property 'fullName' of null
2017-07-01T16:40:31.913287+00:00 app[web.1]:     at Object.<anonymous> (/app/out/github/events/github_runner.js:142:67)
2017-07-01T16:40:31.913287+00:00 app[web.1]:     at Generator.next (<anonymous>)
2017-07-01T16:40:31.913288+00:00 app[web.1]:     at /app/out/github/events/github_runner.js:7:71
2017-07-01T16:40:31.913288+00:00 app[web.1]:     at __awaiter (/app/out/github/events/github_runner.js:3:12)
2017-07-01T16:40:31.913289+00:00 app[web.1]:     at runPRRun (/app/out/github/events/github_runner.js:127:48)
2017-07-01T16:40:31.913289+00:00 app[web.1]:     at Object.<anonymous> (/app/out/github/events/github_runner.js:94:31)
2017-07-01T16:40:31.913290+00:00 app[web.1]:     at Generator.next (<anonymous>)
2017-07-01T16:40:31.913290+00:00 app[web.1]:     at fulfilled (/app/out/github/events/github_runner.js:4:58)
2017-07-01T16:40:31.913291+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:103:7)
2017-07-01T16:40:31.913460+00:00 app[web.1]: /app/out/peril.js:12
2017-07-01T16:40:31.913461+00:00 app[web.1]:     throw reason;
2017-07-01T16:40:31.913461+00:00 app[web.1]:     ^
2017-07-01T16:40:31.913462+00:00 app[web.1]: 
```

**Comment by flovilmart** [comment]
seems that the culprit is db.getRepo in my case. perhaps something misconfigured.

**Comment by orta** [comment]
I was thinking the same thing, was just checking your repo :D

**Comment by flovilmart** [comment]
```
  saveGitHubRepo: async (repo: GithubRepo) => {
    info(`Skipping saving github repo with slug: ${repo.fullName} due to no db`)
  },
```

IIUC, because it's defined as a JSON, the repo save is skipped no?

**Comment by orta** [comment]
Yeah, there should be no saving there

**Comment by flovilmart** [comment]
BTW, I don't see that `Skipping saving github repo with slug...` log, so it's not even called.

**Comment by orta** [comment]
Can you try copying this but for your repos, https://github.com/artsy/artsy-danger/blob/master/peril.settings.json#L7

**Comment by orta** [comment]
I think right now, from the looks of this code, there is an assumption that all of the repos would get mentioned in that JSON file

**Comment by orta** [comment]
I don't think that's a good assumption, but that's what this is doing

screen shot 2017-07-01 at 12 49 50

**Comment by flovilmart** [comment]
I’ll check it out! And your right, thst’s Not what I would expect either. Perhaps rules should go away?

**Comment by orta** [comment]
Rules are like "org wide" e.g. apply to _every_ repo, repo should be per-repo.

**Comment by flovilmart** [comment]
I updated the settings with your recommendation, but still:

```
2017-07-01T17:31:36.593390+00:00 app[web.1]: info: [runner] - Event Settings: {
2017-07-01T17:31:36.593391+00:00 app[web.1]:  "commentableID": 10,
2017-07-01T17:31:36.593392+00:00 app[web.1]:  "hasRelatedCommentable": true,
2017-07-01T17:31:36.593392+00:00 app[web.1]:  "isRepoEvent": true,
2017-07-01T17:31:36.593392+00:00 app[web.1]:  "isTriggeredByUser": true,
2017-07-01T17:31:36.593393+00:00 app[web.1]:  "repo": {
2017-07-01T17:31:36.593394+00:00 app[web.1]:   "fullName": "parse-community/peril",
2017-07-01T17:31:36.593394+00:00 app[web.1]:   "id": 111,
2017-07-01T17:31:36.593394+00:00 app[web.1]:   "installationID": 1,
2017-07-01T17:31:36.593395+00:00 app[web.1]:   "rules": {
2017-07-01T17:31:36.593395+00:00 app[web.1]:    "pull_request": "parse-community/peril@dangerfiles/pr.js",
2017-07-01T17:31:36.593396+00:00 app[web.1]:    "issue": "parse-community/peril@dangerfiles/issue.js"
2017-07-01T17:31:36.593396+00:00 app[web.1]:   }
2017-07-01T17:31:36.593397+00:00 app[web.1]:  },
2017-07-01T17:31:36.593397+00:00 app[web.1]:  "repoName": "parse-community/peril",
2017-07-01T17:31:36.593397+00:00 app[web.1]:  "triggeredByUsername": "flovilmart"
2017-07-01T17:31:36.593398+00:00 app[web.1]: }
2017-07-01T17:31:36.627479+00:00 app[web.1]: Error:  TypeError: Cannot read property 'repo' of undefined
2017-07-01T17:31:36.627481+00:00 app[web.1]:     at Object.<anonymous> (/app/out/github/events/github_runner.js:146:40)
2017-07-01T17:31:36.627482+00:00 app[web.1]:     at Generator.next (<anonymous>)
2017-07-01T17:31:36.627482+00:00 app[web.1]:     at /app/out/github/events/github_runner.js:7:71
2017-07-01T17:31:36.627483+00:00 app[web.1]:     at __awaiter (/app/out/github/events/github_runner.js:3:12)
2017-07-01T17:31:36.627484+00:00 app[web.1]:     at runPRRun (/app/out/github/events/github_runner.js:127:48)
2017-07-01T17:31:36.627484+00:00 app[web.1]:     at Object.<anonymous> (/app/out/github/events/github_runner.js:94:31)
2017-07-01T17:31:36.627485+00:00 app[web.1]:     at Generator.next (<anonymous>)
2017-07-01T17:31:36.627485+00:00 app[web.1]:     at fulfilled (/app/out/github/events/github_runner.js:4:58)
2017-07-01T17:31:36.627486+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by flovilmart** [comment]
> but I think it should be fine to run an org rule on a repo without specifying it exists in the repos section

I concur, the repos should be the special cases.

**Comment by flovilmart** [comment]
The payload from the commit doesn't seem to have the pr.head infos.

**Comment by orta** [comment]
This _should_ be good to go, I'm gonna merge and head out for a bit

**Comment by flovilmart** [comment]
Awesome!

**Comment by flovilmart** [comment]
🎉 everthing is working as expected for PR's 🎉

**Comment by orta** [comment]
Ace!

**Pull request merged**
