### PR TITLE
Added configuration to deploy to Artsy kubernetes clusters

### PR DESCRIPTION
**Pull request by bhoggard**
I don't have any CI set up yet. Let me know if that's needed. Maybe on a fork?

### CODE REVIEW

**Comment by orta** [comment]
oh interesting, nice one

**Comment by orta** [comment]
so this is interesting, this stuff is very artsy specific - does it have to exist here? I'm probably fine for it for now but in the long term, I'll probably be moving it on to it's own thing

**Comment by bhoggard** [comment]
We can keep a production one that works as a generic example of a kubernetes deploy. There are only a few lines that are specific to us. I could do that, and move them to our private [substance](https://github.com/artsy/substance/tree/master/kubernetes-services) repo. Shall I do that once you're sure this all works OK? If so, give me a ticket.

**Comment by orta** [comment]
Sure thing 👍

**Pull request merged**
