### PR TITLE
[WIP] Proposal: Dockerize Peril

### PR DESCRIPTION
**Pull request by MaximeHeckel**
If we can tackle the remaining setup  issues ( #18 ), this would help run Peril on mostly any infrastructure and make the setup way simpler.
This is a first step towards dockerizing Peril:

Instructions (for Docker for Mac / Docker for windows:

- Update the required envvars in `docker-compose.yml`

- Run the following commands
```
docker-compose up --build
```

- Go to http://localhost:4040 to get the ngrok url and update/create the Peril integration with it.

- Install the Peril integration on your repos.

Next steps:

- [x] Provide a script to automatize the mongodb setup (there's actually no need to do this as it's done automatically by Peril, maybe #13 fixed this)
- [x] Give the possibility to provide the config variables via envvar in the compose file (is that already the possible ?)
- [x] Fix the compilation errors (in order to build the code while building the docker image, see comment in Dockerfile):
```
node_modules/danger/distribution/api/fetch.d.ts(1,1): error TS2688: Cannot find type definition file for 'es6-promise'.
node_modules/danger/distribution/platforms/GitHub.d.ts(1,1): error TS2688: Cannot find type definition file for 'es6-promise'.
node_modules/danger/distribution/platforms/platform.d.ts(1,1): error TS2688: Cannot find type definition file for 'es6-promise'.
node_modules/danger/distribution/runner/Executor.d.ts(1,1): error TS2688: Cannot find type definition file for 'es6-promise'.
source/danger/danger_runner.ts(35,6): error TS2339: Property 'additionalHeaders' does not exist on type 'GitHub'.
error Command failed with exit code 2.
```

I assumed I could safely ignore those after testing with my config

### CODE REVIEW

**Comment by orta** [comment]
I am totally into this 👍

**Comment by MaximeHeckel** [comment]
@orta Do you know if it's possible to fix or safely ignore the compilation errors mentioned above? (especially the one involving the danger npm package)

**Comment by orta** [comment]
For the first, try `yarn add @types/node-promise`

For the second, ignore it for now. TypeScript will emit JavaScript when there are Type Error, it will work fine

**Comment by orta** [comment]
I'll try make a release of Danger with https://github.com/danger/danger-js/pull/136 - then get #7 merged today

**Comment by MaximeHeckel** [comment]
I tried `yarn add @types/es6-promise` (node-promise doesn't exist) but it ends up conflicting with the ES5 Promise definition:
```
node_modules/@types/es6-promise/index.d.ts(11,15): error TS2300: Duplicate identifier 'Promise'.
node_modules/@types/es6-promise/index.d.ts(42,19): error TS2300: Duplicate identifier 'Promise'.
source/danger/danger_runner.ts(35,6): error TS2339: Property 'additionalHeaders' does not exist on type 'GitHub'.
../../../../../../usr/local/lib/node_modules/typescript/lib/lib.es2015.iterable.d.ts(145,11): error TS2300: Duplicate identifier 'Promise'.
../../../../../../usr/local/lib/node_modules/typescript/lib/lib.es2015.promise.d.ts(24,11): error TS2300: Duplicate identifier 'Promise'.
../../../../../../usr/local/lib/node_modules/typescript/lib/lib.es2015.promise.d.ts(274,13): error TS2300: Duplicate identifier 'Promise'.
../../../../../../usr/local/lib/node_modules/typescript/lib/lib.es2015.symbol.wellknown.d.ts(168,11): error TS2300: Duplicate identifier 'Promise'.
```
Not a big issue since I can, despite that, build the Docker image

**Comment by orta** [comment]
OK, going to run through this now, will write questions (this is also my first time using docker, so if it my Qs seems newbieish, it's because they are)

**Comment by orta** [comment]
Should `docker-compose.yml` be renamed to `docker-compose.example.yml` and the `docker-compose.yml` be in gitignore?

**Comment by orta** [comment]
think it's pretty cool that ngrok is in there :D

**Comment by orta** [comment]
screen shot 2017-02-05 at 1 56 42 pm

OK, this looks good - I'm a little unsure about what the dev experience would look like using docker?

I know that I can use [VS Code with the attached node process](https://blog.docker.com/2016/07/live-debugging-docker/), it does look like this currently is statically built on `docker up`, do we want to have something like `nodemon` (in TS?) running when working locally. 

I am assuming then pressing save on a change inside _my_ folder would pass it through to the docker vm/image and then restart the node service

**Comment by MaximeHeckel** [comment]
We can rename `docker-compose.yml` in `docker-compose.example.yml` the user will either use it's own or can still require that file via `docker-compose -f FILENAME`.
Concerning the dev experience:

- This PR is really focused first on running the actual project to use it
- You can dev and have a file watch via docker by modifying the docker-compose file as such
(I didn't test it for this case but usually I do that for my own projects using docker for mac)
```
 peril:
    build: .
    ports:
      - "5000:5000"
    links:
      - "mongodb"
    volumes:
      - .:/app
    command: yarn compile
    environment:
     ...
```
We can save that file as `docker-compose.dev.yml` for example.

This is totally independent on whether you're using nodemon or typescript (it works with my projects using webpack-dev-server pretty well :) ) so I guess using VS Code debugging tool should also work (I haven't yet used VS code much so I can't really tell but I'll give it a try whenever I have time)

**Comment by MaximeHeckel** [comment]
@orta I just added a `docker-compose.dev.yml`
You can run `docker-compose -f docker-compose.dev.yml` this will mount your local folder inside the peril docker container, and I changed the command from `yarn start` to `yarn compile` to watch for changes. Looks like it works :) :

http://recordit.co/WVxAfsInhx (maybe you'll have to copy/past this link in your browser to access the actual gif)

Let me know your thoughts on this

**Comment by orta** [comment]
Amazing - looks perfect, how did I miss this comment! Yep - IMO this looks 👍

**Comment by MaximeHeckel** [comment]
Oh maybe the README needs to be updated with the docker instructions (as separate instructions)? It can be done in another PR

**Comment by orta** [comment]
Sure, that's cool with me 👍

**Pull request merged**
