### PR TITLE
Include babel-polyfill

### PR DESCRIPTION
**Pull request by mxstbr**
This fixes the regenerator runtime error from #223

### CODE REVIEW

**Comment by orta** [comment]
Yeah, this feels fine to me 👍

**Comment by mxstbr** [comment]
It's already in the dependencies so I assume it must've gone missing somewhere along the way.

The other potential fix would be to just not transpile async/await anymore now that Node supports it natively, but that obviously limits backwards compat for old Node versions.

**Comment by mxstbr** [comment]
This works for me in prod btw

**Comment by orta** [comment]
Ace

**Comment by orta** [comment]
Hah, I think the invite bot needs to be able to detect if it's sent an invite already

**Pull request merged**
