### PR TITLE
Show all env vars in dangerfile

### PR DESCRIPTION
**Pull request by orta**
:O

### CODE REVIEW

**Comment by orta** [comment]
Alright - well that was obviously an affective attack vector :D

Luckily my ENV is pretty empty on this computer. Tomorrow's task, sandboxing.

**Comment by alloy** [comment]
For this reason, iirc, CIs like Travis don’t expose secret env vars to PRs from forks.

**Comment by orta** [comment]
I originally thought I had turned on process separation inside Jest-runner, but even then I guess it would still have access to the same host ENV vars

**Comment by alloy** [comment]
Dunno about Jest, but you can definitely normally start processes without giving them access to all environment variables. Nonetheless, security is not that simple, what are you _really_ trying to achieve?

**Comment by orta** [comment]
Safely eval-ing JS I don't trust without breaking my machine

**Comment by alloy** [comment]
It really depends what exactly you want to be doing, but in general, if you're going to execute other people's code on your machines, you probably want to run like a VM or something.

**Comment by orta** [comment]
Aye, I am, and I've just not locked it down yet 👍

**Comment by orta** [comment]
Ah, hah, well, that is a good one ^ that undefined is the sandboxed env vars (as I've not pushed a commit to update the dangerfile )

**Comment by orta** [comment]
Alright, looks like it's time to make my own org for peril testing 👍

**Pull request merged**
