### PR TITLE
WIP refactoring, and using new API

### PR DESCRIPTION
**Pull request by orta**
Hrm, it's been a while since I looked at this.

I think my goal was to make a feature so that you can only allow PRs from org members to eval Dangerfiles.

### CODE REVIEW

**Comment by orta** [comment]
This tuned into a mega-PR - but we're back on track now. See https://github.com/PerilTest/PerilPRTester/pull/5

**Comment by orta** [comment]
Main changes: 

* Much better logging.
* Fixed a lot of the terminology internally (note: this will require re-registering existing integrations 0 the database name, and the collection name has changed )
* No storing of access tokens in the db, they are so short lived anyway.

**Comment by orta** [comment]
@MaximeHeckel not sure if you're using this in production but you will have an issue migrating and will need to re-add the integration

**Comment by MaximeHeckel** [comment]
@orta Thank you for the notice!
I'm just using it on a staging env at the moment

**Pull request merged**
