### PR TITLE
Adding more details to PERIL_BOT_USER_ID docs

### PR DESCRIPTION
**Pull request by felipesabino**
I expanded a bit the docs on how do get the bot id for those not that familiar with Github API.

I also managed to get it via the GraphQL API, but was not sure how it would fit the docs. I will leave the query here just in case anyone figures it out in the future how to not be so verbose

```graphql
query BotIdForIssueOrPullRequest($url: URI!) {
  resource(url: $url) {
    __typename
    ...pr
    ...issue
  }
}

fragment issue on Issue {
  comments(first: 100) {
    nodes {
      author {
        ...author
      }
    }
  }
}

fragment pr on PullRequest {
  comments(first: 10) {
    nodes {
      author {
        ...author
      }
    }
  }
}

fragment author on Bot {
  login
  databaseId
}
```

and the data would be just the PR or Issue URL, no id handling needed

```json
{
  "url": "https://api.github.com/repos/[org]/[repo]/issues/[pr_or_issue_id]"
}
```

### CODE REVIEW

**Comment by orta** [comment]
yeah,  this is great 👍

**Comment by orta** [comment]
I wonder if there are ways in which we can automate getting the id too - could in theory post an issue (maybe on the settings repo), get the ID, then delete it

**Comment by felipesabino** [comment]
> I wonder if there are ways in which we can automate getting the id too - could in theory post an issue (maybe on the settings repo), get the ID, then delete it

Thought a bit about that but as I am not familiar with the code base yet, I could not figure it out how to store it properly.

AFAIK he default is to have no DB but instead just store the JSON settings in memory, so I wasn't so keen on creating a new issue on every server boot and couldn't figure it out yet how to have this application-wise state while also being backwards compatible.

**Comment by orta** [comment]
Hrm, it could post in the repo - with the instructions for setting up the bot ID?

- Create an issue
- Check the bot id in the new issue, update the text with the heroku command above
- Let the admin close the issue 

That should be stateless?

**Comment by felipesabino** [comment]
> That should be stateless?

If we can find that such issue was already posted using the API to prevent duplicates, otherwise we will be on a issue posting loop for every server boot until the admin fixes it.

Well, may be that's ok as it will rarely happens and I am just being pedantic...

**Pull request merged**
